### ISSUE TITLE
BlockOffset::plane_offset()

### ISSUE THREAD

**Issue by rom1v** [xiph/rav1e#1062]
The function `BlockOffset::plane_offset()` is supposed to give the offset of a block in plane coordinates.

However, that's not exactly what the implementation does:

https://github.com/xiph/rav1e/blob/64cf7a982a69b2461d9db1d5ab184eedb765992b/src/context.rs#L1170-L1181

In particular, if `xdec` or `ydec` is 1, then the last bit of `x_offset` and `y_offset` is discarded, because it first right-shifts before left-shifting.

IMO, the expected behavior is this one:

```diff
diff --git a/src/context.rs b/src/context.rs
index ef7b267..c31b7af 100644
--- a/src/context.rs
+++ b/src/context.rs
@@ -1175,8 +1175,8 @@ impl BlockOffset {
     let y_offset = self.y & LOCAL_BLOCK_MASK;
 
     PlaneOffset {
-        x: po.x + (x_offset as isize >> plane.xdec << BLOCK_TO_PLANE_SHIFT),
-        y: po.y + (y_offset as isize >> plane.ydec << BLOCK_TO_PLANE_SHIFT)
+        x: po.x + (x_offset << BLOCK_TO_PLANE_SHIFT >> plane.xdec) as isize,
+        y: po.y + (y_offset << BLOCK_TO_PLANE_SHIFT >> plane.ydec) as isize,
     }
   }

```

But with this behavior, decoding tests fail. For example:

```
cargo test --features=decode_test test_encode_decode::chroma_sampling_aom
```

I think that the function must be fixed to correctly give the plane coordinates, and that callers should set the last bit to 0 if they need to. But I'm not sure what caller should do that.

It's probably related to c74fb90ea05c2477c3b0530e6e49e07dd30f35ca cc @ycho.

Thank you for your help.

---

By the way, I think that there is no need to compute the superblock offset and the block offset inside the superblock separately:

```diff
diff --git a/src/context.rs b/src/context.rs
index ef7b267..f3c2eed 100644
--- a/src/context.rs
+++ b/src/context.rs
@@ -1169,14 +1169,9 @@ impl BlockOffset {
 
   /// Offset of the top-left pixel of this block.
   pub fn plane_offset(&self, plane: &PlaneConfig) -> PlaneOffset {
-    let po = self.sb_offset().plane_offset(plane);
-
-    let x_offset = self.x & LOCAL_BLOCK_MASK;
-    let y_offset = self.y & LOCAL_BLOCK_MASK;
-
     PlaneOffset {
-        x: po.x + (x_offset as isize >> plane.xdec << BLOCK_TO_PLANE_SHIFT),
-        y: po.y + (y_offset as isize >> plane.ydec << BLOCK_TO_PLANE_SHIFT)
+        x: (self.x >> plane.xdec << BLOCK_TO_PLANE_SHIFT) as isize,
+        y: (self.y >> plane.ydec << BLOCK_TO_PLANE_SHIFT) as isize,
     }
   }
```

**Comment by ycho** [comment]
Hi Romain, I am sorry to see that this part of the code struggled you. It also confuses me always, even though I see many many times.
You may have already tried (but seems not since you mentioned nowhere), if you apply your change " x: po.x + (x_offset << BLOCK_TO_PLANE_SHIFT >> plane.xdec) as isize", it works for block sizes >= 8x8 (by the time I wrote this patch there is no rectangular blk sizes though). However, block sizes 4x4 will not work, assuming we use 4:2:0 chroma format.

The reason why we must do "if xdec or ydec is 1, then the last bit of x_offset and y_offset is discard" is that with 420 chroma format, there is four corresponding luma 4x4 blks for one chroma 4x4 in a 8x8 block. And the chroma 4x4 is only encoded when the last 4x4 luma block is finished encoding.
Now, if you look at the block offset of that last 4x4 luma, it is always odd number, for both x and y for 420 case. From  odd block offset, we need map corresponding block offset of chroma and finally pixel offset (i.e. plane offset in the codebase).

Hope this helps you understand why it is required.
Hence it is necessary to do first right-shifts before left-shifting.

**Comment by ycho** [comment]
Btw, I think I should have split that old commit c74fb90 into to, since it contains one bug fix and unrelated one improvement of factoring out the block of code for calculating plane offset for chroma block.

**Comment by rom1v** [comment]
@ycho Thank you for your explanation :+1:

The block offset is always expressed in `MI_SIZE`×`MI_SIZE` (4×4) luma blocks, while the output plane offset is expressed in coordinates according to the plane config (luma or chroma). So a 4×4 block cause a 4:2:0 chroma block to span several MI.

**Comment by rom1v** [comment]
(I opened a PR about the last part of this post: https://github.com/xiph/rav1e/pull/1067)
