### ISSUE TITLE
Improve --low_latency command line option

### ISSUE THREAD

**Issue by rom1v** [xiph/rav1e#1224]
`--low-latency` is a boolean option, which takes a value (`false` by default).

This is both unnecessary (in general, either we specify the option it or we don't) and very confusing: `rav1e ... --low_latency` means `low_latency` **disabled** (the default is `false`!). `rav1e ... --low_latency true` enabled it.

The behavior should be changed so that `low_latency` is disabled if the option is not present, and enable if it is present.

https://github.com/xiph/rav1e/blob/cd3ef475ba6a2a7d9832e78dbc296f64e6e7a859/src/bin/common.rs#L162-L167

**Comment by ycho** [comment]
Just giving " --low_latency" w/o true or false makes it low_latency disabled?
I agree on what you said, if default is false, then I prefer that it become true when giving "--low-latency".

**Comment by vladimir-kazakov** [comment]
> Just giving " --low_latency" w/o true or false makes it low_latency disabled?

This is the old behavior, when low_latency was an option. In this case, you had to specify `true` to enable low latency.

In #1228 I changed this option to a flag, which means that there is no need to provide true or false anymore. If the flag is present, it enables the low latency mode; otherwise, it's disabled.
