### ISSUE TITLE
simplify some command line options/arguments

### ISSUE THREAD

**Issue by kodabb** [xiph/rav1e#1247]
a couple of suggestions/minor changes for the cli/api to be more similar with other encoder

1. `--bitrate` should use kb/s not b/s
2. "0" and "9" for the `speed` option do not reflect any actual value and are rather confusing (just by looking at it you can't tell if 0 is the slowest or 9 is), would be nice if some proper preset names were used
3. `tile_cols_log2` and `tile_rows_log2` should not be exposed in log2 but a normal decimal number should be used

**Comment by ycho** [comment]
1. It is alreayd in Kilo Bits. Pls check with "./target/release/rav1e --help"
"    -b, --bitrate <BITRATE>                        
            Bitrate (kbps)"

2. Yes, it can be confusing to many users who likes x264 styles and I believe we can have one for rav1e. Pls note that some other video codes also use speed levels, ex: libvpx (cpu-used 0 ~ 8) or svt-av1 (m0~m8).

3. log2 values are coded in the bitstream, so I think we provide exact that way first.

**Comment by rzumer** [comment]
Personally I find the speed parameter to be intuitive. Higher number => more speed makes sense. Besides --speed 0 which is quasi-exhaustive/"placebo", I think it may be hard to name the other levels now, since they are not currently tuned with specific speed targets in mind yet as far as I know.

>     3\. log2 values are coded in the bitstream, so I think we provide exact that way first.

I understand the rationale and it makes sense to me to expose the parameter this way through the API, but not via CLI, which should be more user-friendly. To people unfamiliar with the AV1 specification it is unintuitive. Does anyone find it easier to specify the exponent instead of the actual number of tiles, or is there a use case I am missing?

**Comment by ycho** [comment]
Just knew that the bitrate has not been multiplied by 1000, so the author (derf) has a patch for it: https://git.xiph.org/?p=users/tterribe/rav1e.git;a=commit;h=3f178a5cf0e8

**Comment by ycho** [comment]
Now, --bitrate is really in Kbps!
Merged: https://github.com/xiph/rav1e/commit/5814bd029577ffd8720f1bb8a8bdccd06e50bba0
