### ISSUE TITLE
NEON SIMD

### ISSUE THREAD

**Issue by EwoutH** [xiph/rav1e#1276]
It would be cool to see some NEON assembly code added to rav1e. Just like AVX2 and SSSE3 code was used from dav1d and aom, NEON could be ported from those projects. Current rav1e has [these](https://github.com/xiph/rav1e/tree/master/src/x86) optimizations for x86. From that list the following modules are also available in NEON from either dav1d or aom:

- [mc.S](https://code.videolan.org/videolan/dav1d/blob/master/src/arm/64/mc.S) from dav1d
- [sad_neon.c](https://aomedia.googlesource.com/aom/+/master/aom_dsp/arm/sad_neon.c?autodive=0%2F%2F) from aom

Maybe @mstorsjo and/or @barrbrain would be interested to integrate this?

**Comment by barrbrain** [comment]
One thing I've considered but not yet opened an issue for: We need some structure around integrating a much larger volume of asm from dav1d (and possibly libaom). So far I've preserved provenance by applying patches from dav1d with `git format-patch`, `git am` and a path filter. This doesn't scale well to the amount of work that has been done in dav1d since then.

More specific to this issue, we have currently only integrated x86 asm with nasm syntax. The NEON assembly from dav1d is in GAS syntax, so we would need to extend the build to support it.

On the other hand, the sad_neon.c from aom lends itself to being ported to Rust NEON intrinsics, when they are ready.

**Comment by EwoutH** [comment]
Potentially also [cdef.S](https://code.videolan.org/videolan/dav1d/blob/master/src/arm/64/cdef.S) and [itx.S](https://code.videolan.org/videolan/dav1d/blob/master/src/arm/64/itx.S) from dav1d

**Comment by barrbrain** [comment]
Much of this was addressed in PRs linked to issue #2376.  The CDEF assembly was integrated in #2575. A translation of SAD was added in PR #2358.
