### ISSUE TITLE
Top-down partition splitting to all 4x4 blocks causes decoding failure

### ISSUE THREAD

**Issue by rzumer** [xiph/rav1e#1377]
Reproduced on `nyan.y4m` (4:2:0, 8-bit). Disabled almost every feature, so only DCT transform, DC prediction, no loop filtering, `-s 10`, etc.

In the top-down partitioning function, `must_split` was set to true if the current partition is larger than 4x4. Rectangular partitioning was also commented out.

The result is that aom cannot decode the first frame.
```
Warning: Failed to decode frame 1: Corrupt frame detected
Warning: Additional information: Failed to decode tile data
```

[encoded.tar.gz](https://github.com/xiph/rav1e/files/3317372/encoded.tar.gz)

**Comment by ycho** [comment]
Not sure whether you have directly changed the below line 

  // Always split if the current partition is too large
  let must_split = (tile_bo.0.x + bsw as usize > ts.mi_width
    || tile_bo.0.y + bsh as usize > ts.mi_height
    || bsize.greater_than(BlockSize::BLOCK_64X64))
    && is_square;

let must_split = bsize.greater_than(BlockSize::BLOCK_4X4);
If so, then I guess sth is broken in partition coding....

Instead, what I did that always worked for splitting to all fixed 4x4s is to enforce the partition as SPLIT for the
else if block "else if (must_split || (bsize > fi.min_partition_size && is_square))
    && ( ... ) { 
// Skip all the code in this block,
// and even skip rdo_partition_decision() then do only below line
  partition = PartitionType::PARTITION_SPLIT;   //<===== THIS! }

as in https://github.com/ycho/rav1e/commit/c3c22188f5f870cc103e4eb52fc5994b8d7e0432
(from my old Feb branch, https://github.com/ycho/rav1e/commits/fixed_size_partition)

I often needed to enforce fixed size partition in order to debug and fix the broken coding modes or RDO of them. So, it should work, I hope!

**Comment by rzumer** [comment]
It's possible that I did something wrong, or some other factor in the configuration caused problems... if someone else tests and cannot reproduce, feel free to close.

**Comment by ycho** [comment]
Not reproducible and demonstrated how to do fixed size (4x4s in this case) topdown partitioning in https://github.com/ycho/rav1e/tree/fixed_size_partition_4x4

<img width="1652" alt="Screen Shot 2019-09-09 at 12 47 05 PM" src="https://user-images.githubusercontent.com/10123259/64561592-f925ac80-d2ff-11e9-8fbe-f62e64a14354.png">
