### ISSUE TITLE
Duplicate MAX_AREA_SB

### ISSUE THREAD

**Issue by tdaede** [xiph/rav1e#1451]
https://github.com/xiph/rav1e/pull/1356 duplicates some logic inside TilingInfo::new() for maximum area computation. We should only do it once.

**Comment by rzumer** [comment]
Can you please point out what is duplicated? I took a look at both sides, searching for "MAX_AREA_SB" in files and the AV1 specification return no result and I don't see how #1356 is related to "maximum area computation".

**Comment by rzumer** [comment]
It looks like #1356 was entirely a duplicate, besides the rate calculation. If I remember correctly, the rate is dynamic due to the temporal scaling, and calculating it only when setting up the tile distribution at the beginning of the encode is incorrect, so I propose simply reverting #1356.

I also suggest changing the name of the `TilingInfo` constructor. In my opinion, `new()` implies a basic constructor that sets fields based on the values provided, perhaps returning a `Result` if any validation is done. If it can "disobey" the input parameters, it should be clearer from the naming (e.g. `from_target_tiles()` or similar).
