### ISSUE TITLE
use const-fn when we can

### ISSUE THREAD

**Issue by lu-zero** [xiph/rav1e#1464]
It is an issue to track the language [metaissue](https://github.com/rust-lang/rust/issues/57563) as more support lands in stable.

**Comment by shssoichiro** [comment]
Clippy has a lint for this which is disabled by default: https://rust-lang.github.io/rust-clippy/master/index.html#missing_const_for_fn

However, the reason it's disabled by default is because it is a WIP and has false positives if used on stable. We should keep an eye on this to see if it becomes better at some point in the future.

**Comment by shssoichiro** [comment]
We've implemented this in the majority of places where it makes sense
