### ISSUE TITLE
Stop doing two transposes for each transform

### ISSUE THREAD

**Issue by KyleSiefring** [xiph/rav1e#1761]
This looks pretty simple. The only functional changes that I see having to be done is removing the transposes and changing the scan order arrays.

I might have missed something, though.

**Comment by ycho** [comment]
> This looks pretty simple. The only functional changes that I see having to be done is removing the transposes and changing the scan order arrays.
> 
> I might have missed something, though.

I don't see where we need to use scan order arrays when doing 2-d transforms?
Given the process in video compression that a step of scanning coefficients is happening only after transform is applied.
Also the reason for doing two transposes is, in one transform stage of of two stages of transforms (which dimension is entirely decided by whether the input elements are stored in a row, i.e. consecutive memory) requires to store input and its output in a consecutive memory for memory access (yes, CPU caches) efficiency reason.
If you start horizontal transform first, that is 1st stage and does not need transform.
Then in the 2nd stage, because each input is column, we have to transpose each column into row. Then apply 1d transforms there, and transpose again the result in order to have column vectors/outputs.

**Comment by KyleSiefring** [comment]
The scanning I'm talking about is happening here. https://github.com/xiph/rav1e/blob/master/src/context.rs#L3974

I want to change the scan order used here, so that we don't need to do the second transpose. I'm a confused by your mention of memory efficiency, since I don't see any code requiring sequential accesses that have to be across specifically columns or specifically rows.

**Comment by ycho** [comment]
Yeah, I think if you have given further context of "during coefficient coding" in the title of this PR, I haven't left unrelavant comment.
Like, "When coefficients are coded", Stop doing two transposes for each transform
Or, Stop doing two transposes for each transform "during coefficient coding"

**Comment by ycho** [comment]
Isn't this done before?

**Comment by KyleSiefring** [comment]
Closed by #1955
