### ISSUE TITLE
Integrate av-metrics to rav1e CLI

### ISSUE THREAD

**Issue by barrbrain** [xiph/rav1e#1762]
Originally drafted in pull request #1589, the [av-metrics](https://github.com/rust-av/av-metrics) crate was created for general use in Rust AV projects. It is now ready to be integrated into the rav1e CLI. This will be useful for tracking objective quality during encoding without additional tools. It may also be useful for dynamic collection of metrics while exploring encoding parameters.

**Comment by de-sh** [comment]
I would like to help with this :)

**Comment by barrbrain** [comment]
@de-sh If you need any guidance, project discussion often happens at the #daala IRC channel on [freenode.net](https://webchat.freenode.net) and you are free to ask questions on this issue also. Note that due to IRC spam, posting to the channel requires a [registered nickname](https://freenode.net/kb/answer/registration).

**Comment by de-sh** [comment]
So I link in the av_metrics module in the `Cago.toml` file and then, so that I don't break things, keep the PSNR flag while adding the metrics flag to call all the metrics methods.

Then I make a new Enum to store symbol denoting which method I called instead of a binary(bool) to show if PSNR was called.
