### ISSUE TITLE
NASM too old on ubuntu 18.04 (LTS)

### ISSUE THREAD

**Issue by KyleSiefring** [xiph/rav1e#2289]
The current instructions simply say to install nasm from apt. I plan to update to 20.04 soon, but it would be nice to have better install support and instructions.

I'm just going to resort to compiling and installing nasm until I update.

**Comment by Urhengulas** [comment]
@KyleSiefring 

I would like to help with that, but what is the exact problem? 
`nasm` seems to be available on ubuntu 20.04 (and also on other platforms, e.g. fedora32)

**Comment by 1480c1** [comment]
Would it be possible for the nasm module to support yasm?

**Comment by veikk0** [comment]
@Urhengulas

The version of NASM available in the repositories of Ubuntu 18.04 is 2.13.02, while rav1e requires a newer version (2.14 or newer, if I'm reading [the relevant commit](https://github.com/xiph/rav1e/pull/2223/commits/7156bb2288eebfb875861cdacfeadc0c84bcb463#diff-a7b0a2dee0126cddf994326e705a91eaR175) correctly). 18.04 is an LTS release and will be around for quite a while. This is probably also the case for quite a few other distros as well.

I personally won't be upgrading to 20.04 for a while. A simple guide to building an up-to-date NASM and how to build rav1e with it instead of the system-wide NASM would be much appreciated. I'm currently not using or testing out rav1e because I don't know how to do the second step.

So far I have this for downloading and compiling NASM:
>wget https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/nasm-2.14.02.tar.bz2 && tar xjvf nasm-2.14.02.tar.bz2 && cd nasm-2.14.02 && sh configure && make -j$(nproc)

**Comment by Urhengulas** [comment]
I found [`nasm-mozilla`](https://packages.ubuntu.com/bionic/nasm-mozilla) in the ubuntu 18.04 package registry, which seems to provide `nasm-2.14.2`.

Going to test it and see if one can run rav1e with it.
