### ISSUE TITLE
Cdef apply assembly isn't being run

### ISSUE THREAD

**Issue by KyleSiefring** [xiph/rav1e#2360]
18450431e83a3407f539a2abb6130d10306b9f9e disabled cdef assembly by providing u16 pixels.

**Comment by xiphmont** [comment]
Kyle: Can you be more specific?  cdef always used u16 in these specific pathways in practice, it just hadn't hardwired it.

**Comment by shssoichiro** [comment]
The input has always been u16, but the output has been generic between u8 and u16. Now the output is hardcoded to u16, which we don't have ASM for and is causing some significant slowdowns for 8-bit encodes.

**Comment by xiphmont** [comment]
Ah.  OK, on it.  I dislike the explosion of generic combinatorics, but that'll get fixed when CDEF no longer requires 16 bit input.

**Comment by xiphmont** [comment]
Current status: Watercooler meeting 7/10/2020 made it known that dav1d now has new assembly for CDEF that removes the 16-bit input restriction (eg, code no longer has to flag border pixels using an in-band value in the frame data).  We should adopt this new assembly immediately (along with equivalent Rust) so that there's no longer any need to go back and forth between Pixel:T and Pixel:u16 throughout the loop filter RDO loop.  Getting the new assembly in is a little work, but then we get a permanent fix for 2360 almost free, and get cleaner code as well.

**Comment by vibhoothiiaanand** [comment]
@xiphmont Hi,
We are not using any of dav1d's CDEF patches as rav1e has diverged, 
We are having our own CDEF assembly from @KyleSiefring AFAIK,
https://github.com/xiph/rav1e/pull/1581
I was also checking history: https://github.com/xiph/rav1e/commits/master/src/x86/cdef_sse.asm
https://github.com/xiph/rav1e/commits/master/src/x86/cdef.asm

When we are also merging the dav1d assembly by release, we are skipping CDEF. So not sure how straightforward will can adopt dav1d's assembly.

Maybe, @barrbrain can comment bit more as he has done dav1d porting for x86 more, IIRC dav1d has more/different filters than us currently.

**Comment by KyleSiefring** [comment]
@xiphmont This is the current function definition for cdef in dav1d. https://code.videolan.org/videolan/dav1d/-/blob/master/src/cdef.h#L54

It looks like the optimization is implemented only when none of the edge flags are set. It's also in place and has pointers to the top and left pixels.
