### ISSUE TITLE
Investigate the js api for encoders available

### ISSUE THREAD

**Issue by lu-zero** [xiph/rav1e#2384]
Would be nice to come up with something that isn't completely unknown to our possible target users.

**Comment by Urhengulas** [comment]
# Research
I did some research around existing media encoders in JavaScript and am going to share my take so far.
Firstly I noticed that there are not that many media encoders in js and often they are "just" wrapper around encoding tools (e.g. ffmpeg).

The API I think is best to take as a role model is **[fluent-ffmpeg](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg)** (only for node.js).

Another noteworthy one is [ffmpeg.wasm](https://github.com/ffmpegwasm/ffmpeg.wasm), which is a bit similiar to what we are doing. It's a js library based on webassembly (ports ffmpeg (C/C++) via emscipten).

## fluent-ffmpeg
```js
const enc = ffmpeg('/path/to/your_movie.avi')
  // video options
  .videoBitrate(1024).videoCodec('divx').aspect('16:9')
  .size('50%')       .fps(24)
  // audio options
  .noAudio()
  // output options
  .format('avi')
  // event handler
  .on('end', function() {
    console.log('file has been converted succesfully');
  })
  .on('error', function(err) {
    console.log('an error happened: ' + err.message);
  });

const outStream = fs.createWriteStream('/path/to/output.avi');

// start processing and write to stream
enc.pipe(outStream, {end: true});
```

### what i like
* easy trailing of methods
* event handlers like 'progress' (transcoding progress information), or 'end' (processing finished)
* lots of options

## ffmpeg.wasm
It's an interesting project, but also quite different, because it is based on emscripten. 

# api v0.1
Based on the research and the current minimal js-api I came up with a js-workflow to implement next with wasm-bindgen:

```js
// struct Frame
let frame = createFrame();

// struct Context
let encoder = createEncoder();

// struct Context
let packet = encoder.encode(frame);
```

Next steps will include:
* multiple frames into one packet
* own input data
* configure encoder

---

Thoughts? Feedback?

Find my notes here: https://www.notion.so/urhengulas/API-Design-0dfc787efe4649ac9d2fae45d1e8ff84

**Comment by Urhengulas** [comment]
# v0.1

#2399 implements v0.1 of the js-api.

## design
The interface looks slightly different than proposed:
```ts
import { Encoder, Frame, Packet } from "rav1e";

const enc: Encoder = new Encoder();
const f: Frame = enc.newFrame();

for (let i = 0; i < 10; i++) {
    enc.sendFrame(f);
}
enc.flush();

for (let i = 0; i < 20; i++) {
    try {
        let p: Packet = enc.encodeNext();
        console.log(p.display())
    } catch (error) {
        console.log(error);
    }
}
```

## next steps
asa v0.1 is accepted the next steps are going to be:
* own input data (probably `MediaStreamTrack` or a `canvas`)
* encoder configuration

**Comment by lu-zero** [comment]
How do you configure the encoder? I guess you should add a `Config` in the mix. We can discuss on IRC the fine details :)

**Comment by Urhengulas** [comment]
# promises and futures
Another interesting feature are Promises and Futures. We might want to think about integrating them into the API at some point.

* https://rustwasm.github.io/wasm-bindgen/reference/js-promises-and-rust-futures.html

**Comment by Urhengulas** [comment]
We will be using the this [project board](https://github.com/xiph/rav1e/projects/19) for keeping track of feature ideas and progress.
