### ISSUE TITLE
Deployment for rav1e_js example website

### ISSUE THREAD

**Issue by Urhengulas** [xiph/rav1e#2424]
@lu-zero Had the great idea to deploy the [rav1e_js](https://github.com/xiph/rav1e/tree/master/rav1e_js) demo website and combine it with some kind of performance report.

Currently https://github.com/xiph/rav1e/pull/2423 is open to update the example website. I'd like to take this one as basis.

Let's gather ideas:
* [ ] As a user I want to run the performance test with one click
* [ ] As a user I want to easily submit my test results (e.g. google form)
* [ ] ...

Regarding deployment: What is the easiest mean for it? I have in mind:
* gh-pages
* heroku

**Comment by vibhoothiiaanand** [comment]
I did try to test the deployment yesterday, the main issue I found is,
1. For deployment, we require the wasm compiled ones, we either should provide as binaries for the website to use as a source
2. Secondly, AFAIK the GitHub Actions supports serving webpages esp react/gatsby/js where the source is in the root, here the case is different where it is in `src/rav1e_js/www`  which will be quite problematic and we should figure how we can do it easier
3. Thirdly, it sounds easier to do such a thing in GitLab as with the GitLab CI, we can just take alpine, apk add necessary ones, build it, serve it. So the first thing is figuring whether we can do something similar on GitHub actions. Note that we need to first build wasm then this, so that is one thing which I am unsure.
I am testing the demo whether it is plausible in Github here: https://github.com/vibhoothiiaanand/rav1e-demo
I will update it
4. As it react, we can serve statically AFAIK since I have tested with npm production build and serve, seems we can be static, not 100% sure, so I assume you are having heroku for that, 

Not sure what is the use-case of heroku? 

So regarding issues, I would encourage to be in GitHub itself, since we do not want any additional burden IMO

**Comment by vibhoothiiaanand** [comment]
So moving forward, 

Good part
- I managed to hook up and initiate the serving with custom folder using GitHub Actions

Referring to https://create-react-app.dev/docs/deployment/#github-pages

So with gh-pages we can deploy it using `gh-pages`

I have made some more changes, but the GitHub Actions is acting weird like this is created pre-GitHub-action era, so it does not go well with the actions

So,
- Need to find an action which does what `gh-pages` does
- Have #2416 land first since we need that else it will be long runs
- Cleanup the script and run along with main js

Demo URL: https://vibhoothiiaanand.github.io/rav1e-demo/
Repo: https://github.com/vibhoothiiaanand/rav1e-demo/

**Comment by barrbrain** [comment]
Now that the JS API has moved to <https://github.com/rust-av/rav1e_js>, we should open an issue there to continue this work.
Unfortunately, we cannot simply transfer the issue because the repositories have different owners.
Closing since the JS API was removed in #2649.
