### ISSUE TITLE
Travis tests in CI does not seem to include "RAV1E_CPU_TARGET=rust" run

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#2452]
I suspect this because my pending WIP PR #2396 shows numerous cargo test fails when run locally with
RAV1E_CPU_TARGET=rust, but Travis CI only shows the fail for arm target, and furthermore only for the function that does not have asm code.

@barrbrain

**Comment by vibhoothiiaanand** [comment]
The normal tests(GitHub Actions do not have the rust `RAV1E_CPU_TARGET` runs, I think we also need to have one additional run for normal targets(x86_64) to make sure it does not break on all platforms.

**Comment by barrbrain** [comment]
We currently run generic checks and `x86_64` checks with GitHub Actions, while we run `aarch64` checks on Travis. Since the `aarch64` assembly is less complete than for `x86_64`, there is a little more coverage of Rust-native functions on Travis. As @vibhoothiiaanand suggested, we should add a `RAV1E_CPU_TARGET=rust` run to GitHub Actions to ensure full coverage. There is an intermediate solution available - extending the `check_asm` feature to cover all integrated assembly - but this feature was only ever enabled in GitLab CI.

**Comment by ycho** [comment]
@shssoichiro, Thank you for fixing this!
