### ISSUE TITLE
Prepare a v0.3.4

### ISSUE THREAD

**Issue by lu-zero** [xiph/rav1e#2527]
Please link candidate fixes, so far:
-  9c4c1111deb8ed3283d8a807d83d77312d115ed3 - unbreak android builds
-  9742a07f7885cc2e62cc8f61e07b23dc8991aceb - unbreak the C-API

**Comment by vibhoothiiaanand** [comment]
okay so I was extracting list of commits from v0.3.3 to current master.
http://dgql.org/~mindfreeze/full_list_origin.txt

Few more possible candidates could be 
* 89f6b8c6 - Use thiserror instead of err-derive (6 months ago)
* de515e08 - Suppress the nth(0) clippy warning (6 months ago)
* 26821b7e - Fix debug_assert with high quantizers (#2222) (5 months ago)
* 4b500718 - Fix panic on specific inputs with high quantizers (#2220) (5 months ago)
* af286dbb - Add NASM minimum version check (#2223) (5 months ago)
* 6ec594e3 - Resolve build errors for fuzzer (5 months ago)
* 9f6cdbc1 - Fix deblocking of horizontal edges for narrow frames (5 months ago)
* 5c79c637 - Abort pass encoding without a bitrate target in CLI (4 months ago)
* 58dbbf16 - Fix version flag (#2258) (4 months ago)
* 73d7dd36 - Assert on deblocking a plane with subsampling > 1. (4 months ago) [Not sure??]
* 8aabfc07 - Avoid building serde with default feature set (#2362) (3 months ago)
* 132be5cf - Pin the nasm-rs version (3 months ago) [??? Maybe]
* c41325d0 - Bug fix: inter-tx split cause desync with bottomup partition search (4 weeks ago)
* ea9cbb31 - Support arbitrary SAR anamorphic video (5 days ago) [Maybe???]
* 348eef71 - Interpret 0:0 SAR as 1:1 (#2523) (3 days ago) [Part of previous one Maybe??]

**Comment by jamrial** [comment]
ea9cbb314f2d69ebc7e78101164c1e68c11c689f introduces a new C API function. Is that allowed in point releases?

**Comment by vibhoothiiaanand** [comment]
@jamrial seems your right, I was confused, 
One reason I thought is, it might behave wrongly, but not a severe or blocker

**Comment by lu-zero** [comment]
most of the commits you listed are already in

**Comment by lu-zero** [comment]
v0.3.4 has been released :)
