### ISSUE TITLE
Deploy Arm64 builds for macOS and Windows on (pre-)release

### ISSUE THREAD

**Issue by EwoutH** [xiph/rav1e#2652]
It would be great to have pre-build binaries for the `aarch64-apple-darwin` and `aarch64-pc-windows-msvc` [targets](https://doc.rust-lang.org/beta/rustc/platform-support.html#tier-2) deployed to GitHub on releases and pre-releases.

**Comment by lu-zero** [comment]
- `aarch64-apple-darwin` requires bigSur in order to link correctly and bigSur is not yet stable on github that I know, we have plans to leverage the kind offer from https://www.macstadium.com/, but it isn't in place yet.
- `aarch64-pc-windows-msvc` should just be a matter of adding the correct target on the Windows deploy.

@EwoutH if you send a patch for the latter would be great while I'll figure out how to set up the CI runner on the macstadium system.

**Comment by lu-zero** [comment]
Do you have time to test if the bigSur images are stable enough now?

**Comment by EwoutH** [comment]
Cargo C builds pass, both to the `x86_64-apple-darwin` and `aarch64-apple-darwin` targets. Regular Cargo build and tests fail.

https://github.com/EwoutH/rav1e/actions/runs/704716606
```
error[E0659]: `ChromaSampling` is ambiguous (glob import vs glob import in the same module)
```

**Comment by EwoutH** [comment]
Status update: With #2688 and #2711 both Windows and macOS Arm64 targets are now added to the regular CI. I will look this weekend into adding them to the deploy CI.

One problem is that there will be two `rav1e.exe` files. What is the preferred solution for deployment? `rav1e-x64.exe` and `rav1e-arm64.exe`? Or keep them as `rav1e.exe`, but put them both in a separate ZIP file?

**Comment by lu-zero** [comment]
separate zip files sounds a good idea.

**Comment by Felixkruemel** [comment]
What's with builds for normal aarch64 Linux installations? That would be great too and should not be that hard

**Comment by Luni-4** [comment]
We don't have an `aarch64` target for Windows anymore, so we can close this one
