### ISSUE TITLE
capi's check_frame_size() ignores still_picture mode

### ISSUE THREAD

**Issue by joedrago** [xiph/rav1e#2730]
**Description:**

rav1e is supported in libavif via it's C API (`capi.rs`). When encoding single images (not sequences) with libavif, libavif will engage `still_picture` mode, but despite recent changes to rav1e to allow for images smaller than `16x16` when in `still_picture` mode, the `capi.rs` layer still restricts smaller images even when the `still_picture` flag is set.

**To Reproduce**
Attempt to encode an image smaller than 16x16 (tested with 1x1 and 3x3) with the C API and `still_picture` enabled. The failure path can be seen using libavif's `avifenc`, such as:

    avifenc -c rav1e 1x1.png 1x1.avif

I've verified if I loosen the restriction in `capi.rs`'s `check_frame_size()`, the encode succeeds. The results aren't ideal (see #151), but this ceases to be a failure case.

**Expected behavior**
Enabling `still_picture` via the C API should allow setting `"width"` and `"height"` (also via the C API) to values less than 16. 

Version: v0.4.1
Operating system: All known to work with libavif (Windows, Linux, macOS)

**Comment by rzumer** [comment]
It might be better to remove this check when parsing parameters, and possibly returning an error after the configuration is set if the parameters are incompatible (i.e. still picture mode disabled, and frame size < 16x16). Otherwise, still picture mode must be enabled prior to setting the frame size, and frame size must be validated when changing the still picture mode flag in case it is disabled after setting the size to something below 16x16.

That said, I am pretty sure that frame sizes below 16x16 are legal in AV1 video streams as long as the bitstream level is set to maximum parameters, and rav1e does set this level for all encoded streams, so assuming there's no issue involving small inter frames, we can probably remove this restriction completely.

**Comment by joedrago** [comment]
I'm certainly open to anything that'd alleviate this issue; I didn't mean to prescribe any specific solution (sorry about that). I agree that something that is immune to order-of-operations errors when configuring is a better answer.
