### ISSUE TITLE
Mapping speed level control in one place

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#290]
It would be more maintainable if we do map speed level to activation of modes in one place, 
instead of having "if fi.speed > x " conditions several places over the codebase.

Also, skip is currently disabled from level > 1, but I expect forthcoming inter mode will need it almost at all speed levels.

**Comment by tterribe** [comment]
I think centralizing the management of the speed levels is a good idea, but I'm not a fan of the libaom approach of having a single SPEED_FEATURES struct which stores all of the flags and parameters that get set by these speed levels, which then has to be plumbed around everywhere. The "if fi.speed > x" tests are certainly convenient (that's why people wrote the existing code like that).

One approach that I think is a good middle ground is to never use a literal constant value for "x", but always a named constant. We can then put the definition of all of these constants in one place, to make management easy. This approach is still compatible with pulling out some parameters to a higher level (e.g., the list of intra modes we're going to search).

**Comment by lu-zero** [comment]
I guess some depends on what kind of control we want to expose to the user.
Being able to turn-on/off/override features explicitly can be quite good, but that would mean that we'd have:
``` rust
if cfg.enabled(FOO) { do_stuff_foo(...) }
...

let modes = cfg.intra_modes()
```

I do not have a strong opinion and it is something that can be decided later, but probably @dwbuiten has one. :)

**Comment by ycho** [comment]
Again, my desired way of implementing speed control is "more maintainable" and less mistake prone by developers. If that holds, I welcome any kinds.

**Comment by tterribe** [comment]
My first inclination for, e.g., a list of intra modes, would be to have a const array indexed by the speed level (which would live with all of the other threshold constants).
