### ISSUE TITLE
Add a mode to test encode/decode mismatch

### ISSUE THREAD

**Issue by smarter** [xiph/rav1e#3]
Probably by relying on aomdec being on the PATH

**Comment by negge** [comment]
Luca is porting his libvpx bindings to libaom so we can link and call this with a debug build.

**Comment by lu-zero** [comment]
I prepared the crate for that, right now it just uses pkg-config to pick the library though

**Comment by lu-zero** [comment]
With [this](https://github.com/rust-av/aom-rs/commit/fb155c92a5aec65940291f50dbb0e7b34b649889) I can build the bindings against a custom build.

There are the following caveats: 
- right now it uses the cmake build system, the configure line would need to be converted to `-D` equivalents.
- we'd have to use a custom fork to set all the custom features we need.

Alternatively I could extend our `build.rs` and maybe keep this under a default-disable feature since building libaom would take quite a bit of time.

**Comment by tdaede** [comment]
The build time is 100% worth it for tests.
I think switching to the cmake build system for the README is fine.

**Comment by lu-zero** [comment]
If you can convert it to the right `-D` I can try to get something in working shape today.
