### ISSUE TITLE
Enable rustfmt checking locally and on Travis-ci

### ISSUE THREAD

**Issue by mbebenita** [xiph/rav1e#31]

**Comment by smarter** [comment]
Current status: https://github.com/tdaede/rav1e/pull/43

**Comment by xuguangxin** [comment]
@mbebenita , @smarter 
After one year later, "cargo fmt" still not move [some code style](https://github.com/xiph/rav1e/pull/1259/commits/342c1750b0bb6ff40e393424edbccdbafec118eb) from nightly to stable.
Currently, many [codes ](https://github.com/xiph/rav1e/pull/1259/commits/a77427d25d7cd04f4691bbcc4f7f9c838bdf2614#diff-afb2ab3fe17077dcacb9d8b9f1546945L155)do not have the right style. 
How about we accept reality, use stable "cargo fmt" and enforce it in pre-commit hook and travis?
https://github.com/xiph/rav1e/pull/1259 will enforce this

thanks

**Comment by tdaede** [comment]
The main sticking point is fn_args_layout, which is still not stable. We can either live with the default for this option or continue to not enforce rustfmt.

**Comment by YaLTeR** [comment]
Currently most of the options we use are stable on the **beta** branch of `rustfmt`.

There are three left-over unstable options:
- `comment_width`: this one actually has no effect because we don't set `wrap_comments`;
- `match_arm_blocks`: I'd argue it doesn't really make much difference and can be dropped;
- `ignore`: this can be dropped with the reformat.

I'll make a PR to drop these options (and also a couple of other ones that are set to the default values). After that, there are two options:
- run and set up the beta `rustfmt` right before the crate release;
- wait until the current beta `rustfmt` reaches stable (15th Aug 2019).
