### ISSUE TITLE
Low quality chroma on inter frames

### ISSUE THREAD

**Issue by tdaede** [xiph/rav1e#470]
http://daddesio.com/~andrew/files/stockholm_original.png

http://daddesio.com/~andrew/files/stockholm_rav1e.png

**Comment by fbossen** [comment]
Now sure how this was produced in the first place, but should look better now 7fe6aecf37ad0a99d552113fd5de9a580f0872dd

**Comment by daddesio** [comment]
I can confirm that bf537275 fixes the issue, and that the latest rav1e version (48326cdc) also looks good.

http://daddesio.com/~andrew/files/rav1e/stockholm_e4674776.png (bad chroma)
http://daddesio.com/~andrew/files/rav1e/stockholm_bf537275.png (good)
http://daddesio.com/~andrew/files/rav1e/stockholm_48326cdc.png (good)

(also, it's not a problem with the e4674776 Appveyor build because it looks the same when I compile from source.)
