### ISSUE TITLE
Standalone rav1e compilation fails on proc-macro-hac (experimental feature) (Win10-64bit).

### ISSUE THREAD

**Issue by Murmur** [xiph/rav1e#742]
Link to media_autobuild_suite(ffmpeg,mp4box,rav1e,etc.. compilation on Windows)
**standalone rav1e compilation fails on proc-macro-hac (experimental feature).**
https://github.com/jb-alvarado/media-autobuild_suite/issues/979

Link to [logs.zip file ](https://0x0.st/slnY.zip)for detailed error messages and the relevant part of the errors quoted below. Ideas how to fix this? I don't know anything about rustc compiler and rav1e packiging scheme.

```
┌ rav1e git ......................................... [Recently updated]
├ Running submodule...
├ Running build...
Likely error:
    |
130 |     syn::custom_keyword!(export);
    |     ^^^^^^^^^^^^^^^^^^^
error: aborting due to previous error
For more information about this error, try `rustc --explain E0658`.
error: Could not compile `proc-macro-hack`.
$ cd build/rav1e-git
$ rustc --explain E0658
An unstable feature was used.

```

**Comment by lu-zero** [comment]
It seems an upstream bug, you may try to `cargo update` and report back.

**Comment by lu-zero** [comment]
Related https://github.com/dtolnay/paste/issues/6

**Comment by Murmur** [comment]
@lu-zero  I run the following commands but same error message.
[logs.zip](https://0x0.st/sUPK.zip)
```
run mintty console
$ cd build/rav1e-git
$ cargo update
edit build/media-autobuild_suite.ini
rav1e=0
run mintty console
$ ./update_suite.sh
run media-autobuild_suite.bat script
```

```
┌ rav1e git ............................................ [Updates found]
├ Running submodule...
├ Running build...
Likely error:
    |
130 |     syn::custom_keyword!(export);
    |     ^^^^^^^^^^^^^^^^^^^
error: aborting due to previous error
For more information about this error, try `rustc --explain E0658`.
error: Could not compile `proc-macro-hack`.
warning: build failed, waiting for other jobs to finish...
error: build failed
build failed. Check C:/projects/media-autobuild_suite/media-autobuild_suite/build/rav1e-git/ab-suite.build.log
This is required for other packages, so this script will exit. Creating diagnostics file...
All relevant logs have been anonymously uploaded to https://0x0.st/sUPK.zip
Copy and paste [logs.zip](https://0x0.st/sUPK.zip) in the GitHub issue.
```

**Comment by lu-zero** [comment]
The logs do not tell much regarding which version of rust and which commands are you using.

Could you please provide 
- `rustc --version`
- which is your environment/shell (msys2? native powershell?)
- manually run `cargo update && cargo build`

**Comment by andrerochasp** [comment]
I'm having the same problem. I guess Media-Autobuild-Suite uses msys2 as shell. Following is the output of commands above:

$ cd build/rav1e-git/
Administrador@doomsdayp /trunk/build/rav1e-git
$ ls
aom_build     build.sh     data                  README.md
appveyor.yml  Cargo.lock   LICENSE               rustfmt.toml
benches       Cargo.toml   license_template.txt  src
build.rs      clippy.toml  PATENTS               target
Administrador@doomsdayp /trunk/build/rav1e-git
$ rustc --version
rustc 1.29.2 (17a9dc751 2018-10-05)
Administrador@doomsdayp /trunk/build/rav1e-git
$ cargo update
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/tdaede/nasm-rs.git`
    Updating aho-corasick v0.6.8 -> v0.6.9
    Updating byteorder v1.2.6 -> v1.2.7
    Updating cfg-if v0.1.5 -> v0.1.6
    Updating cmake v0.1.34 -> v0.1.35
    Updating csv v1.0.1 -> v1.0.2
    Updating failure v0.1.2 -> v0.1.3
    Updating failure_derive v0.1.2 -> v0.1.3
    Updating lazy_static v1.1.0 -> v1.2.0
    Updating log v0.4.5 -> v0.4.6
    Updating memchr v2.0.2 -> v2.1.1
    Updating proc-macro2 v0.4.19 -> v0.4.23
    Updating quote v0.6.8 -> v0.6.10
    Removing rand_core v0.2.1
      Adding rand_core v0.2.2
      Adding rand_core v0.3.0
    Updating regex v1.0.5 -> v1.0.6
    Updating regex-syntax v0.6.2 -> v0.6.3
    Updating ryu v0.2.6 -> v0.2.7
    Updating same-file v1.0.3 -> v1.0.4
    Updating serde v1.0.78 -> v1.0.80
    Updating serde_derive v1.0.78 -> v1.0.80
    Updating serde_json v1.0.27 -> v1.0.33
    Updating simplelog v0.5.2 -> v0.5.3
    Removing syn v0.14.9
    Updating synstructure v0.9.0 -> v0.10.1
    Updating ucd-util v0.1.1 -> v0.1.2
    Updating utf8-ranges v1.0.1 -> v1.0.2
    Updating version_check v0.1.4 -> v0.1.5
    Updating walkdir v2.2.5 -> v2.2.7
    Updating winapi v0.3.5 -> v0.3.6
Administrador@doomsdayp /trunk/build/rav1e-git
$ cargo build
 Downloading proc-macro2 v0.4.23
 Downloading quote v0.6.10
 Downloading winapi v0.3.6
 Downloading cfg-if v0.1.6
 Downloading rand_core v0.2.2
 Downloading rand_core v0.3.0
   Compiling proc-macro2 v0.4.23
   Compiling unicode-xid v0.1.0
   Compiling winapi-x86_64-pc-windows-gnu v0.4.0
   Compiling winapi v0.3.6
   Compiling nasm-rs v0.1.3 (https://github.com/tdaede/nasm-rs.git#7c01c74c)
   Compiling rand_core v0.3.0
   Compiling unicode-width v0.1.5
   Compiling num-traits v0.2.6
   Compiling cfg-if v0.1.6
   Compiling bitflags v1.0.4
   Compiling vec_map v0.8.1
   Compiling rustc-demangle v0.1.9
   Compiling strsim v0.7.0
   Compiling bitstream-io v0.8.1
   Compiling libc v0.2.43
   Compiling y4m v0.3.1
   Compiling textwrap v0.10.0
   Compiling rand_core v0.2.2
   Compiling rav1e v0.1.0 (file:///F:/media-autobuild_suite/build/rav1e-git)
   Compiling quote v0.6.10
   Compiling atty v0.2.11
   Compiling backtrace v0.3.9
   Compiling rand v0.5.5
   Compiling syn v0.15.20
   Compiling clap v2.32.0
   Compiling proc-macro-hack v0.5.1
error[E0658]: non-ident macro paths are experimental (see issue #35896)
   --> F:/media-autobuild_suite/msys64/opt/cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro-hack-0.5.1\src\lib.rs:130:5
    |
130 |     syn::custom_keyword!(export);
    |     ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `proc-macro-hack`.
warning: build failed, waiting for other jobs to finish...
error: build failed
Administrador@doomsdayp /trunk/build/rav1e-git
$

**Comment by andrerochasp** [comment]
I'm having the same problem. I guess Media-Autobuild-Suite uses msys2 as shell. Following is the output of commands above:

$ cd build/rav1e-git/
Administrador@doomsdayp /trunk/build/rav1e-git
$ ls
aom_build build.sh data README.md
appveyor.yml Cargo.lock LICENSE rustfmt.toml
benches Cargo.toml license_template.txt src
build.rs clippy.toml PATENTS target
Administrador@doomsdayp /trunk/build/rav1e-git
$ rustc --version
rustc 1.29.2 (17a9dc751 2018-10-05)
Administrador@doomsdayp /trunk/build/rav1e-git
$ cargo update
Updating registry https://github.com/rust-lang/crates.io-index
Updating git repository https://github.com/tdaede/nasm-rs.git
Updating aho-corasick v0.6.8 -> v0.6.9
Updating byteorder v1.2.6 -> v1.2.7
Updating cfg-if v0.1.5 -> v0.1.6
Updating cmake v0.1.34 -> v0.1.35
Updating csv v1.0.1 -> v1.0.2
Updating failure v0.1.2 -> v0.1.3
Updating failure_derive v0.1.2 -> v0.1.3
Updating lazy_static v1.1.0 -> v1.2.0
Updating log v0.4.5 -> v0.4.6
Updating memchr v2.0.2 -> v2.1.1
Updating proc-macro2 v0.4.19 -> v0.4.23
Updating quote v0.6.8 -> v0.6.10
Removing rand_core v0.2.1
Adding rand_core v0.2.2
Adding rand_core v0.3.0
Updating regex v1.0.5 -> v1.0.6
Updating regex-syntax v0.6.2 -> v0.6.3
Updating ryu v0.2.6 -> v0.2.7
Updating same-file v1.0.3 -> v1.0.4
Updating serde v1.0.78 -> v1.0.80
Updating serde_derive v1.0.78 -> v1.0.80
Updating serde_json v1.0.27 -> v1.0.33
Updating simplelog v0.5.2 -> v0.5.3
Removing syn v0.14.9
Updating synstructure v0.9.0 -> v0.10.1
Updating ucd-util v0.1.1 -> v0.1.2
Updating utf8-ranges v1.0.1 -> v1.0.2
Updating version_check v0.1.4 -> v0.1.5
Updating walkdir v2.2.5 -> v2.2.7
Updating winapi v0.3.5 -> v0.3.6
Administrador@doomsdayp /trunk/build/rav1e-git
$ cargo build
Downloading proc-macro2 v0.4.23
Downloading quote v0.6.10
Downloading winapi v0.3.6
Downloading cfg-if v0.1.6
Downloading rand_core v0.2.2
Downloading rand_core v0.3.0
Compiling proc-macro2 v0.4.23
Compiling unicode-xid v0.1.0
Compiling winapi-x86_64-pc-windows-gnu v0.4.0
Compiling winapi v0.3.6
Compiling nasm-rs v0.1.3 (https://github.com/tdaede/nasm-rs.git#7c01c74c)
Compiling rand_core v0.3.0
Compiling unicode-width v0.1.5
Compiling num-traits v0.2.6
Compiling cfg-if v0.1.6
Compiling bitflags v1.0.4
Compiling vec_map v0.8.1
Compiling rustc-demangle v0.1.9
Compiling strsim v0.7.0
Compiling bitstream-io v0.8.1
Compiling libc v0.2.43
Compiling y4m v0.3.1
Compiling textwrap v0.10.0
Compiling rand_core v0.2.2
Compiling rav1e v0.1.0 (file:///F:/media-autobuild_suite/build/rav1e-git)
Compiling quote v0.6.10
Compiling atty v0.2.11
Compiling backtrace v0.3.9
Compiling rand v0.5.5
Compiling syn v0.15.20
Compiling clap v2.32.0
Compiling proc-macro-hack v0.5.1
error[E0658]: non-ident macro paths are experimental (see issue #35896)
--> F:/media-autobuild_suite/msys64/opt/cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro-hack-0.5.1\src\lib.rs:130:5
|
130 | syn::custom_keyword!(export);
| ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try rustc --explain E0658.
error: Could not compile proc-macro-hack.
warning: build failed, waiting for other jobs to finish...
error: build failed
Administrador@doomsdayp /trunk/build/rav1e-git
$

**Comment by lu-zero** [comment]
> `rustc 1.29.2 (17a9dc751 2018-10-05)`

Please update to the current stable.

**Comment by Murmur** [comment]
@lu-zero Thank you, I run `rustup update` in Mintty console, took few minutes rust tools being updated to 1.30.1 release. Compilcation works again.

**Comment by tdaede** [comment]
OK, should we require syn > 0.15.21?
